/**
 * The generator's one hook into the real renderer (Phase 156).
 *
 * ## Why the generator needs a hook at all
 *
 * The application menu bar and the tray menu are built in MAIN, and main is up
 * before any window exists. Phase 153's marks are rasterized in the RENDERER,
 * from the codicon font, through `getComputedStyle` on the same stylesheet the
 * visible glyph beside them reads. So main cannot ask for them at the moment it
 * needs them.
 *
 * The phase's answer is a set generated at build time into
 * `src/main/menu-icons.generated.ts`, the way `file-icons.generated.ts` already
 * establishes. The refusal that shaped this file is that the generated set must
 * come FROM Phase 153's own code path rather than from a second copy of it. So
 * `build/generate-menu-icons.mjs` starts the REAL built renderer, waits for
 * `warmMenuIcons()` to finish, and reads the cache that filled. There is one
 * rasterizer in this product and the generated bytes are its output.
 *
 * ## Why it is a probe rather than a plain export
 *
 * A window property has to exist for `executeJavaScript` to reach it, and a
 * property written at module scope of a file the app always loads would sit in
 * the entry chunk of a person's launch. Phase 127 moved fourteen such drives
 * behind `probe-loader.ts`, which imports `probe-registry.ts` only when the
 * renderer's own URL carries `harness=1`. This registrar is called from there,
 * so nothing here is loaded by a real launch.
 *
 * It assigns one function to `window` and changes nothing else.
 */

import { warmedMenuIcons, warmMenuIcons } from './codicon-menu-icon';

declare global {
  interface Window {
    __gmuxP156MenuIcons?: () => Promise<Record<string, string>>;
  }
}

export function registerP156MenuIconsDrive(): void {
  window.__gmuxP156MenuIcons = async (): Promise<Record<string, string>> => {
    // `warmMenuIcons` is idempotent and returns the same promise every time,
    // so awaiting it here joins the pass App.tsx already started rather than
    // starting a second one.
    await warmMenuIcons();
    return warmedMenuIcons();
  };
}
