/**
 * The managed status line script, RUN (Phase 182).
 *
 * The rest of this phase's checks read the script's text or its reader. This
 * one hands the real generated bytes to a real `/bin/sh` through the same
 * `sh -c '<quoted path>'` shape Claude Code uses for a `type: "command"`
 * status line, feeds it a payload in the measured shape from
 * docs/research/72 section 10.5, and reads what a real loopback server got.
 *
 * THE THREE THINGS ONLY A RUN CAN PROVE:
 *
 *  1. IT PRINTS NOTHING. Everything the person sees in their own pane depends
 *     on this one byte count being zero, and no amount of reading the script
 *     proves it. The startup payload, the turn payload and the refused
 *     payloads all go through it and stdout stays empty in every case.
 *  2. IT POSTS THE FOUR NUMBERS AND NOTHING ELSE. The payload also carries the
 *     person's cwd, their transcript path, their prompt id, their session id,
 *     their model, their workspace and a cost block. The body is asserted key
 *     by key, and every one of those is asserted absent by its own sentinel.
 *  3. IT READS THE RIGHT `used_percentage`. There are two in the payload:
 *     `context_window` has one and it is a different number. A script that
 *     grepped the payload rather than the braces would post the wrong one and
 *     nothing downstream could tell.
 *
 * It spawns `/bin/sh` and binds one loopback server, both of its own, in a
 * directory of its own that it removes. It reads nothing under anybody's home
 * and starts no agent.
 */

import { execFile } from 'node:child_process';
import { createServer, type Server } from 'node:http';
import { chmodSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { promisify } from 'node:util';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import {
  TAP_THROTTLE_SECONDS,
  claudeStatusLineScript,
  decodeConfigKey,
  parseTapBody,
  shellQuote
} from '../statusline';

const run = promisify(execFile);

const SESSION = 'a1b2c3d4-0000-4000-8000-000000000001';
const TOKEN = '0123456789abcdef0123456789abcdef';
const NOW_SECONDS = 1_790_000_000;

/** The measured payload shape, with a sentinel in every personal field. */
function payload(over: Record<string, unknown> = {}): string {
  return JSON.stringify({
    cwd: 'SENTINEL_CWD',
    transcript_path: 'SENTINEL_TRANSCRIPT',
    prompt_id: 'SENTINEL_PROMPT',
    session_id: 'SENTINEL_AGENT_SESSION',
    session_name: 'SENTINEL_NAME',
    version: '2.1.252',
    model: { display_name: 'Opus', id: 'SENTINEL_MODEL_ID' },
    workspace: { current_dir: 'SENTINEL_DIR', project_dir: 'SENTINEL_PROJECT' },
    cost: { total_cost_usd: 1.25, total_duration_ms: 9000 },
    context_window: {
      context_window_size: 200000,
      used_percentage: 77,
      remaining_percentage: 23
    },
    rate_limits: {
      five_hour: { used_percentage: 58, resets_at: NOW_SECONDS + 3600 },
      seven_day: { used_percentage: 41, resets_at: NOW_SECONDS + 200000 }
    },
    ...over
  });
}

interface Post {
  path: string;
  body: string;
}

let dir: string;
let script: string;
let server: Server;
let posts: Post[];
let port: number;

beforeAll(async () => {
  dir = mkdtempSync(join(tmpdir(), 'p182-script-'));
  const settingsDir = join(dir, 'claude');
  const stampDir = join(settingsDir, 'stamps');
  mkdirSync(stampDir, { recursive: true });
  script = join(settingsDir, 'tortie-statusline.sh');
  writeFileSync(script, claudeStatusLineScript({ settingsDir, stampDir }), 'utf8');
  chmodSync(script, 0o755);
  posts = [];
  server = createServer((req, res) => {
    let body = '';
    req.on('data', (c: Buffer) => {
      body += c.toString('utf8');
    });
    req.on('end', () => {
      posts.push({ path: req.url ?? '', body });
      res.statusCode = 200;
      res.end();
    });
  });
  port = await new Promise<number>((resolve) => {
    server.listen(0, '127.0.0.1', () => {
      resolve((server.address() as { port: number }).port);
    });
  });
  // The settings file the script reads its destination out of, in the exact
  // shape src/main/activity/hooks.ts writes.
  writeFileSync(
    join(settingsDir, `${SESSION}.json`),
    JSON.stringify({
      allowedHttpHookUrls: [`http://127.0.0.1:${port}/*`],
      hooks: {
        Stop: [
          {
            hooks: [
              {
                type: 'http',
                url: `http://127.0.0.1:${port}/h/${TOKEN}?e=Stop`
              }
            ]
          }
        ]
      },
      statusLine: { type: 'command', command: shellQuote(script) }
    }),
    'utf8'
  );
});

afterAll(() => {
  server.close();
  rmSync(dir, { recursive: true, force: true });
});

/** One invocation, exactly as claude makes it: `sh -c '<quoted path>'`. */
async function invoke(
  stdin: string,
  env: Record<string, string> = {}
): Promise<{ stdout: string; stderr: string }> {
  const child = run('/bin/sh', ['-c', shellQuote(script)], {
    env: {
      PATH: process.env['PATH'] ?? '/usr/bin:/bin',
      GMUX_MANAGED: '1',
      GMUX_SESSION_ID: SESSION,
      ...env
    }
  });
  child.child.stdin?.end(stdin);
  return child;
}

/** Clear the throttle stamp so each case starts from an open gate. */
function unthrottle(): void {
  rmSync(join(dir, 'claude', 'stamps', SESSION), { force: true });
}

function fields(body: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const pair of body.split('&')) {
    const eq = pair.indexOf('=');
    out[pair.slice(0, eq)] = decodeURIComponent(pair.slice(eq + 1));
  }
  return out;
}

describe('the run', () => {
  it('prints nothing and posts the four numbers', async () => {
    unthrottle();
    posts = [];
    const { stdout, stderr } = await invoke(payload());
    // THE STDOUT NEGATIVE CONTROL. A byte here is a row in the person's pane.
    expect(stdout).toBe('');
    expect(stderr).toBe('');
    expect(posts.length).toBe(1);
    expect(posts[0]?.path).toBe(`/u/${TOKEN}`);
    expect(fields(posts[0]?.body ?? '')).toEqual({
      v: '1',
      s: SESSION,
      cfg: '',
      five_pct: '58',
      five_reset: String(NOW_SECONDS + 3600),
      seven_pct: '41',
      seven_reset: String(NOW_SECONDS + 200000)
    });
  });

  it('posts nothing personal, over a payload where every field is a sentinel', async () => {
    unthrottle();
    posts = [];
    await invoke(payload());
    const body = posts[0]?.body ?? '';
    for (const sentinel of [
      'SENTINEL_CWD',
      'SENTINEL_TRANSCRIPT',
      'SENTINEL_PROMPT',
      'SENTINEL_AGENT_SESSION',
      'SENTINEL_NAME',
      'SENTINEL_MODEL_ID',
      'SENTINEL_DIR',
      'SENTINEL_PROJECT',
      'total_cost_usd',
      '1.25'
    ]) {
      expect(body).not.toContain(sentinel);
    }
  });

  it('reads the rate_limits percentage and not the context window one', async () => {
    unthrottle();
    posts = [];
    await invoke(payload());
    // 77 is context_window.used_percentage in the same payload.
    expect(fields(posts[0]?.body ?? '')['five_pct']).toBe('58');
  });

  it('says nothing at startup, where the key is simply absent', async () => {
    unthrottle();
    posts = [];
    const noLimits = JSON.parse(payload()) as Record<string, unknown>;
    delete noLimits['rate_limits'];
    const { stdout } = await invoke(JSON.stringify(noLimits));
    expect(stdout).toBe('');
    expect(posts).toEqual([]);
  });

  it('says nothing in a pane Tortie did not stamp', async () => {
    unthrottle();
    posts = [];
    await invoke(payload(), { GMUX_MANAGED: '0' });
    expect(posts).toEqual([]);
    unthrottle();
    await invoke(payload(), { GMUX_SESSION_ID: '' });
    expect(posts).toEqual([]);
  });

  it('throttles itself per pane', async () => {
    unthrottle();
    posts = [];
    await invoke(payload());
    await invoke(payload());
    await invoke(payload());
    expect(posts.length).toBe(1);
    expect(TAP_THROTTLE_SECONDS).toBe(15);
  });

  it('carries the config directory exactly, encoded, when one is set', async () => {
    unthrottle();
    posts = [];
    const cfgDir = '/Users/x/Library/Application Support/claude work/';
    await invoke(payload(), { CLAUDE_CONFIG_DIR: cfgDir });
    const cfg = fields(posts[0]?.body ?? '')['cfg'] ?? '';
    // The trailing separator is trimmed on this side too, so a person who
    // writes the directory either way is the same account.
    expect(decodeConfigKey(cfg)).toBe(
      '/Users/x/Library/Application Support/claude work'
    );
  });

  it('survives the phrase rate_limits appearing in a field of its own', async () => {
    unthrottle();
    posts = [];
    await invoke(payload({ session_name: 'my rate_limits notes' }));
    expect(fields(posts[0]?.body ?? '')['five_pct']).toBe('58');
  });

  it('says nothing when the numbers are null rather than absent', async () => {
    unthrottle();
    posts = [];
    await invoke(
      payload({
        rate_limits: { five_hour: null, seven_day: null }
      })
    );
    expect(posts).toEqual([]);
  });

  it('posts a body this phase own reader accepts, end to end', async () => {
    unthrottle();
    posts = [];
    await invoke(payload());
    const sample = parseTapBody(posts[0]?.body ?? '', NOW_SECONDS * 1000);
    expect(sample?.sessionId).toBe(SESSION);
    expect(sample?.fiveHour).toEqual({
      percent: 58,
      resetsAt: (NOW_SECONDS + 3600) * 1000
    });
  });
});
