/**
 * Per-agent launch/resume specs + Codex rollout harvesting.
 *
 * The manifest's job (research 02): capture each agent's conversation id as
 * early as possible so a reboot can arm `<agent> resume <id>`:
 *  - claude: PRE-ASSIGN — generate a uuid, launch `claude --session-id <uuid>`,
 *    resume later with `claude --resume <uuid> ...original flags` (flags are
 *    NOT restored by --resume, so the original extras are re-passed).
 *  - codex: no pre-assignment exists (v0.12x) — HARVEST the uuid from the
 *    rollout file `~/.codex/sessions/YYYY/MM/DD/rollout-<ts>-<uuid>.jsonl[.zst]`
 *    created right after spawn (may later move into an archived_sessions dir).
 *  - shell: plain $SHELL; argv+cwd only, nothing to resume.
 *
 * Ownership: src/main/manifest/**. Pure Node (no Electron import) so it can
 * be unit-tested outside the app.
 */

import { randomUUID } from 'node:crypto';
import { existsSync } from 'node:fs';
import { open, readdir, stat } from 'node:fs/promises';
import { homedir } from 'node:os';
import { basename, join } from 'node:path';
import * as parcelWatcher from '@parcel/watcher';
import type { AgentKind } from '@shared/types';

// ---------------------------------------------------------------------------
// Launch specs
// ---------------------------------------------------------------------------

/** How the agent's conversation id is obtained. */
export type IdCaptureMode =
  /** Id generated by gmux and passed at launch (claude --session-id). */
  | 'preassigned'
  /** Id harvested from the agent's on-disk store after spawn (codex). */
  | 'rollout-watch'
  /** No conversation id exists (plain shells). */
  | 'none';

/**
 * Everything the sessions service needs to spawn an agent and everything the
 * manifest needs to resurrect it later.
 */
export interface AgentLaunchSpec {
  agent: AgentKind;
  /** Full argv to launch now (argv[0] is the command). */
  argv: string[];
  /** Known at launch only for 'preassigned' agents. */
  agentSessionId?: string;
  /**
   * Full argv that resumes this exact conversation after reboot. Undefined
   * until the id is known (codex: call codexResumeArgv after harvest) and
   * for shells (a restore just opens a fresh shell).
   */
  resumeArgv?: string[];
  /** Environment deltas to apply at spawn (none needed today). */
  env?: Record<string, string>;
  idCapture: IdCaptureMode;
}

/**
 * Build the launch spec for a new session.
 *
 * @param agent      which agent to run
 * @param extraArgs  user-supplied extra flags (e.g. --model, --add-dir).
 *                   Recorded into BOTH argv and resumeArgv because resume
 *                   does not re-apply launch flags (research 02).
 * @param binPath    RESOLVED absolute path of the agent binary (Bug A: the
 *                   manifest stores absolute paths in argv AND resume_argv
 *                   so restores survive PATH drift). The caller resolves via
 *                   src/main/tmux/resolve.ts; bare names remain the default
 *                   only for tests/legacy callers.
 */
export function buildLaunchSpec(
  agent: AgentKind,
  extraArgs: readonly string[] = [],
  binPath?: string
): AgentLaunchSpec {
  switch (agent) {
    case 'claude': {
      // Strongest primitive in the field: deterministic pre-assignment.
      const uuid = randomUUID();
      const bin = binPath ?? 'claude';
      return {
        agent,
        agentSessionId: uuid,
        argv: [bin, '--session-id', uuid, ...extraArgs],
        resumeArgv: claudeResumeArgv(uuid, extraArgs, bin),
        idCapture: 'preassigned'
      };
    }
    case 'codex':
      // No --session-id equivalent; the uuid is harvested post-spawn via
      // watchForRollout(). resumeArgv stays undefined until then.
      return {
        agent,
        argv: [binPath ?? 'codex', ...extraArgs],
        idCapture: 'rollout-watch'
      };
    case 'shell': {
      // GUI-launched Electron inherits a minimal env; SHELL may be unset.
      const shell = binPath ?? process.env['SHELL'] ?? '/bin/zsh';
      return {
        agent,
        argv: [shell, ...extraArgs],
        idCapture: 'none'
      };
    }
  }
}

/** `claude --resume <uuid>` + the original extra flags (not auto-restored). */
export function claudeResumeArgv(
  sessionId: string,
  extraArgs: readonly string[] = [],
  bin = 'claude'
): string[] {
  return [bin, '--resume', sessionId, ...extraArgs];
}

/** `codex resume <uuid>` + the original extra flags. */
export function codexResumeArgv(
  sessionId: string,
  extraArgs: readonly string[] = [],
  bin = 'codex'
): string[] {
  return [bin, 'resume', sessionId, ...extraArgs];
}

// ---------------------------------------------------------------------------
// Codex rollout harvesting
// ---------------------------------------------------------------------------

/**
 * rollout-YYYY-MM-DDThh-mm-ss-<uuid>.jsonl or .jsonl.zst
 * (filename layout documented in codex-rs rollout/src/list.rs).
 */
const ROLLOUT_RE =
  /^rollout-(\d{4})-(\d{2})-(\d{2})T(\d{2})-(\d{2})-(\d{2})-([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})\.jsonl(\.zst)?$/;

export interface CodexRolloutInfo {
  /** The uuid embedded in the rollout filename — Codex's session id. */
  sessionId: string;
  /** Absolute path of the rollout file when first matched. */
  rolloutPath: string;
  /** Ready-made `codex resume <uuid>` argv (extras NOT included — append). */
  resumeArgv: string[];
}

export interface RolloutWatchOptions {
  /** Override ~/.codex (tests / CODEX_HOME users). */
  codexHome?: string;
  /** Give up after this long. Default 120 s. */
  timeoutMs?: number;
  /** Polling fallback interval. Default 1000 ms. */
  pollIntervalMs?: number;
  /**
   * How long an unconfirmable candidate (empty file, .zst) may wait for a
   * cwd-confirmed rival before being accepted. Default 3000 ms.
   */
  graceMs?: number;
  /**
   * Binary used in the ready-made resumeArgv — pass the session's recorded
   * ABSOLUTE argv[0] (Bug A: resume must survive PATH drift). Default 'codex'.
   */
  resumeBin?: string;
}

export interface RolloutWatch {
  /** Resolves with the harvested id; rejects on timeout or cancel(). */
  promise: Promise<CodexRolloutInfo>;
  /** Stop watching. The promise rejects with a 'cancelled' error. */
  cancel(): void;
}

/** 'match' = jsonl meta cwd equals ours; 'unknown' = can't tell (yet). */
type CandidateVerdict = 'match' | 'mismatch' | 'unknown';

interface Candidate {
  path: string;
  sessionId: string;
  /** Timestamp parsed from the filename (local time), epoch ms. */
  nameTs: number;
  firstSeen: number;
  verdict: CandidateVerdict;
}

function parseRolloutName(
  fileName: string
): { sessionId: string; nameTs: number } | null {
  const m = ROLLOUT_RE.exec(fileName);
  if (!m) return null;
  const [, y, mo, d, h, mi, s, uuid] = m;
  if (!y || !mo || !d || !h || !mi || !s || !uuid) return null;
  // Filename timestamps are the agent host's local time.
  const nameTs = new Date(
    Number(y),
    Number(mo) - 1,
    Number(d),
    Number(h),
    Number(mi),
    Number(s)
  ).getTime();
  return { sessionId: uuid, nameTs };
}

/**
 * Read the rollout's first JSONL line and compare its recorded cwd to ours.
 * Codex writes a session-meta line first ({..., "payload": {"cwd": ...}}).
 * Returns 'unknown' for .zst (can't parse without a zstd dep), empty files,
 * or unparseable/format-drifted lines.
 */
async function classifyCandidate(
  path: string,
  wantCwd: string
): Promise<CandidateVerdict> {
  if (path.endsWith('.zst')) return 'unknown';
  let fh;
  try {
    fh = await open(path, 'r');
    const buf = Buffer.alloc(65536);
    const { bytesRead } = await fh.read(buf, 0, buf.length, 0);
    if (bytesRead === 0) return 'unknown'; // just created, not flushed yet
    const text = buf.subarray(0, bytesRead).toString('utf8');
    const nl = text.indexOf('\n');
    const firstLine = nl === -1 ? text : text.slice(0, nl);
    if (nl === -1 && bytesRead === buf.length) return 'unknown'; // partial line
    const parsed: unknown = JSON.parse(firstLine);
    if (parsed === null || typeof parsed !== 'object') return 'unknown';
    const obj = parsed as Record<string, unknown>;
    const payload = obj['payload'];
    const cwdRaw =
      payload !== null && typeof payload === 'object'
        ? (payload as Record<string, unknown>)['cwd']
        : obj['cwd'];
    if (typeof cwdRaw !== 'string') return 'unknown';
    return cwdRaw === wantCwd ? 'match' : 'mismatch';
  } catch {
    return 'unknown';
  } finally {
    await fh?.close().catch(() => undefined);
  }
}

/** List rollout files under dir, recursing only into plausible subdirs. */
async function scanForRollouts(
  dir: string,
  depth: number,
  out: string[]
): Promise<void> {
  if (depth > 4) return;
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return; // dir vanished / not yet created — fine
  }
  for (const e of entries) {
    const full = join(dir, e.name);
    if (e.isDirectory()) {
      // sessions/YYYY/MM/DD plus any archived_sessions subdir at any level.
      if (/^\d{4}$/.test(e.name) || /^\d{2}$/.test(e.name) || e.name === 'archived_sessions') {
        await scanForRollouts(full, depth + 1, out);
      }
    } else if (ROLLOUT_RE.test(e.name)) {
      out.push(full);
    }
  }
}

/**
 * Watch for the Codex rollout file created after a spawn at `sinceTs` and
 * extract its session uuid.
 *
 * Strategy (research 02 / FINAL-REPORT §2.4 Step 0 point 3):
 *  - @parcel/watcher (FSEvents) subscription on ~/.codex/sessions, plus
 *    ~/.codex/archived_sessions when present — rollouts may be .jsonl or
 *    .jsonl.zst and may MOVE into an archived_sessions dir; the uuid lives
 *    in the filename, so a move never loses it.
 *  - Polling fallback (readdir scan) in case the native watcher fails to
 *    initialize or drops events.
 *  - Disambiguation when several codex sessions start near-simultaneously:
 *    the rollout's first JSONL line records the session cwd; a cwd-confirmed
 *    candidate wins immediately, an unconfirmable one (.zst / still empty)
 *    is accepted after `graceMs` with no confirmed rival.
 */
export function watchForRollout(
  cwd: string,
  sinceTs: number,
  options: RolloutWatchOptions = {}
): RolloutWatch {
  const codexHome = options.codexHome ?? join(homedir(), '.codex');
  const timeoutMs = options.timeoutMs ?? 120_000;
  const pollIntervalMs = options.pollIntervalMs ?? 1_000;
  const graceMs = options.graceMs ?? 3_000;
  const sessionsDir = join(codexHome, 'sessions');
  const archivedDir = join(codexHome, 'archived_sessions');
  // Slack for clock/fs-timestamp skew between our sinceTs and file times.
  const minTs = sinceTs - 2_000;

  const candidates = new Map<string, Candidate>(); // key: sessionId
  const subscriptions: parcelWatcher.AsyncSubscription[] = [];
  let pollTimer: ReturnType<typeof setInterval> | undefined;
  let timeoutTimer: ReturnType<typeof setTimeout> | undefined;
  let settled = false;

  let resolveP!: (v: CodexRolloutInfo) => void;
  let rejectP!: (e: Error) => void;
  const promise = new Promise<CodexRolloutInfo>((resolve, reject) => {
    resolveP = resolve;
    rejectP = reject;
  });

  const cleanup = (): void => {
    if (pollTimer !== undefined) clearInterval(pollTimer);
    if (timeoutTimer !== undefined) clearTimeout(timeoutTimer);
    for (const sub of subscriptions) {
      void sub.unsubscribe().catch(() => undefined);
    }
    subscriptions.length = 0;
  };

  const settle = (info: CodexRolloutInfo | null, err?: Error): void => {
    if (settled) return;
    settled = true;
    cleanup();
    if (info) resolveP(info);
    else rejectP(err ?? new Error('rollout watch failed'));
  };

  const accept = (c: Candidate): void => {
    settle({
      sessionId: c.sessionId,
      rolloutPath: c.path,
      resumeArgv: codexResumeArgv(c.sessionId, [], options.resumeBin ?? 'codex')
    });
  };

  /** Register/refresh one path as a candidate; may settle the watch. */
  const consider = async (path: string): Promise<void> => {
    if (settled) return;
    const parsed = parseRolloutName(basename(path));
    if (!parsed) return;

    // Freshness: filename timestamp (local) OR file mtime must be >= minTs.
    // Either passing is enough — stat can fail after an archive move, and
    // filename time can lag mtime by write latency.
    let fresh = parsed.nameTs >= minTs;
    if (!fresh) {
      try {
        const st = await stat(path);
        fresh = st.mtimeMs >= minTs || st.birthtimeMs >= minTs;
      } catch {
        /* moved away — filename check already said stale */
      }
    }
    if (!fresh) return;

    const existing = candidates.get(parsed.sessionId);
    const cand: Candidate = existing ?? {
      path,
      sessionId: parsed.sessionId,
      nameTs: parsed.nameTs,
      firstSeen: Date.now(),
      verdict: 'unknown'
    };
    cand.path = path; // follow archive moves
    if (cand.verdict === 'unknown') {
      cand.verdict = await classifyCandidate(path, cwd);
    }
    candidates.set(parsed.sessionId, cand);
    decide();
  };

  /** Pick a winner if one is ready. */
  const decide = (): void => {
    if (settled) return;
    const list = [...candidates.values()].filter(
      (c) => c.verdict !== 'mismatch'
    );
    if (list.length === 0) return;
    // Earliest rollout at/after spawn is most likely ours.
    list.sort((a, b) => a.nameTs - b.nameTs);
    const confirmed = list.find((c) => c.verdict === 'match');
    if (confirmed) {
      accept(confirmed);
      return;
    }
    // No confirmation possible (yet): wait out the grace period in case a
    // cwd-confirmed rival shows up or the file gains its meta line.
    const first = list[0];
    if (first && Date.now() - first.firstSeen >= graceMs) accept(first);
  };

  const poll = async (): Promise<void> => {
    if (settled) return;
    const found: string[] = [];
    await scanForRollouts(sessionsDir, 0, found);
    if (existsSync(archivedDir)) {
      await scanForRollouts(archivedDir, 0, found);
    }
    for (const p of found) await consider(p);
    decide(); // re-evaluate grace timers even with no new files
  };

  const onEvents: parcelWatcher.SubscribeCallback = (err, events) => {
    if (settled) return;
    if (err) return; // polling fallback still runs
    for (const evt of events) {
      if (evt.type === 'delete') continue;
      void consider(evt.path);
    }
  };

  // Native watcher (best-effort; polling is the guaranteed path).
  const subscribeTo = async (dir: string): Promise<void> => {
    try {
      if (!existsSync(dir)) return; // poll picks it up once codex creates it
      const sub = await parcelWatcher.subscribe(dir, onEvents);
      if (settled) {
        void sub.unsubscribe().catch(() => undefined);
        return;
      }
      subscriptions.push(sub);
    } catch {
      // FSEvents unavailable or dir race — polling covers us.
    }
  };
  void subscribeTo(sessionsDir);
  void subscribeTo(archivedDir);

  // Polling fallback + initial scan (the file may predate our subscription).
  pollTimer = setInterval(() => void poll(), pollIntervalMs);
  void poll();

  timeoutTimer = setTimeout(() => {
    settle(
      null,
      new Error(
        `Timed out after ${timeoutMs} ms waiting for a Codex rollout in ${sessionsDir} (cwd ${cwd}). ` +
          'The session runs fine, but gmux could not record its resume id.'
      )
    );
  }, timeoutMs);

  return {
    promise,
    cancel: () => settle(null, new Error('rollout watch cancelled'))
  };
}
